# SPDX-FileCopyrightText: 2020 Diego Elio Pettenò
#
# SPDX-License-Identifier: Unlicense

[build-system]
requires = ["setuptools>=30.3.0", "wheel", "setuptools_scm"]

[tool.black]
target-version = ['py35']
